name: Brad Rozran - Software Developer in Chicago
pygments: true

post:
  template: _post.txt
  extensions: md

page:
  template: _page.txt
  extension: md
  editor: ia

exclude:
- assets
- README.md
- Rakefile
